/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSpacesRouteImport } from './routes/app.spaces'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppExploreRouteImport } from './routes/app.explore'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppToolsZImageRouteImport } from './routes/app.tools.z-image'
import { Route as AppToolsVoiceRouteImport } from './routes/app.tools.voice'
import { Route as AppToolsVideoRouteImport } from './routes/app.tools.video'
import { Route as AppToolsUpscalerRouteImport } from './routes/app.tools.upscaler'
import { Route as AppToolsStyleTransferRouteImport } from './routes/app.tools.style-transfer'
import { Route as AppToolsSeedreamEditRouteImport } from './routes/app.tools.seedream-edit'
import { Route as AppToolsSeedreamRouteImport } from './routes/app.tools.seedream'
import { Route as AppToolsRunwayRouteImport } from './routes/app.tools.runway'
import { Route as AppToolsRemoveBackgroundRouteImport } from './routes/app.tools.remove-background'
import { Route as AppToolsRelightRouteImport } from './routes/app.tools.relight'
import { Route as AppToolsReimagineRouteImport } from './routes/app.tools.reimagine'
import { Route as AppToolsImageGenerationRouteImport } from './routes/app.tools.image-generation'
import { Route as AppToolsImageExpandRouteImport } from './routes/app.tools.image-expand'
import { Route as AppToolsGenerativeFillRouteImport } from './routes/app.tools.generative-fill'
import { Route as AppToolsFlux2RouteImport } from './routes/app.tools.flux2'
import { Route as AppToolsFluxKontextRouteImport } from './routes/app.tools.flux-kontext'
import { Route as AppToolsEraserRouteImport } from './routes/app.tools.eraser'
import { Route as ApiPublicMagnificWebhookRouteImport } from './routes/api/public/magnific-webhook'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSpacesRoute = AppSpacesRouteImport.update({
  id: '/spaces',
  path: '/spaces',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsZImageRoute = AppToolsZImageRouteImport.update({
  id: '/tools/z-image',
  path: '/tools/z-image',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsVoiceRoute = AppToolsVoiceRouteImport.update({
  id: '/tools/voice',
  path: '/tools/voice',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsVideoRoute = AppToolsVideoRouteImport.update({
  id: '/tools/video',
  path: '/tools/video',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsUpscalerRoute = AppToolsUpscalerRouteImport.update({
  id: '/tools/upscaler',
  path: '/tools/upscaler',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsStyleTransferRoute = AppToolsStyleTransferRouteImport.update({
  id: '/tools/style-transfer',
  path: '/tools/style-transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsSeedreamEditRoute = AppToolsSeedreamEditRouteImport.update({
  id: '/tools/seedream-edit',
  path: '/tools/seedream-edit',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsSeedreamRoute = AppToolsSeedreamRouteImport.update({
  id: '/tools/seedream',
  path: '/tools/seedream',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRunwayRoute = AppToolsRunwayRouteImport.update({
  id: '/tools/runway',
  path: '/tools/runway',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRemoveBackgroundRoute =
  AppToolsRemoveBackgroundRouteImport.update({
    id: '/tools/remove-background',
    path: '/tools/remove-background',
    getParentRoute: () => AppRoute,
  } as any)
const AppToolsRelightRoute = AppToolsRelightRouteImport.update({
  id: '/tools/relight',
  path: '/tools/relight',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsReimagineRoute = AppToolsReimagineRouteImport.update({
  id: '/tools/reimagine',
  path: '/tools/reimagine',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsImageGenerationRoute = AppToolsImageGenerationRouteImport.update({
  id: '/tools/image-generation',
  path: '/tools/image-generation',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsImageExpandRoute = AppToolsImageExpandRouteImport.update({
  id: '/tools/image-expand',
  path: '/tools/image-expand',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsGenerativeFillRoute = AppToolsGenerativeFillRouteImport.update({
  id: '/tools/generative-fill',
  path: '/tools/generative-fill',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsFlux2Route = AppToolsFlux2RouteImport.update({
  id: '/tools/flux2',
  path: '/tools/flux2',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsFluxKontextRoute = AppToolsFluxKontextRouteImport.update({
  id: '/tools/flux-kontext',
  path: '/tools/flux-kontext',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsEraserRoute = AppToolsEraserRouteImport.update({
  id: '/tools/eraser',
  path: '/tools/eraser',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMagnificWebhookRoute =
  ApiPublicMagnificWebhookRouteImport.update({
    id: '/api/public/magnific-webhook',
    path: '/api/public/magnific-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/explore': typeof AppExploreRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/spaces': typeof AppSpacesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/magnific-webhook': typeof ApiPublicMagnificWebhookRoute
  '/app/tools/eraser': typeof AppToolsEraserRoute
  '/app/tools/flux-kontext': typeof AppToolsFluxKontextRoute
  '/app/tools/flux2': typeof AppToolsFlux2Route
  '/app/tools/generative-fill': typeof AppToolsGenerativeFillRoute
  '/app/tools/image-expand': typeof AppToolsImageExpandRoute
  '/app/tools/image-generation': typeof AppToolsImageGenerationRoute
  '/app/tools/reimagine': typeof AppToolsReimagineRoute
  '/app/tools/relight': typeof AppToolsRelightRoute
  '/app/tools/remove-background': typeof AppToolsRemoveBackgroundRoute
  '/app/tools/runway': typeof AppToolsRunwayRoute
  '/app/tools/seedream': typeof AppToolsSeedreamRoute
  '/app/tools/seedream-edit': typeof AppToolsSeedreamEditRoute
  '/app/tools/style-transfer': typeof AppToolsStyleTransferRoute
  '/app/tools/upscaler': typeof AppToolsUpscalerRoute
  '/app/tools/video': typeof AppToolsVideoRoute
  '/app/tools/voice': typeof AppToolsVoiceRoute
  '/app/tools/z-image': typeof AppToolsZImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/explore': typeof AppExploreRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/spaces': typeof AppSpacesRoute
  '/app': typeof AppIndexRoute
  '/api/public/magnific-webhook': typeof ApiPublicMagnificWebhookRoute
  '/app/tools/eraser': typeof AppToolsEraserRoute
  '/app/tools/flux-kontext': typeof AppToolsFluxKontextRoute
  '/app/tools/flux2': typeof AppToolsFlux2Route
  '/app/tools/generative-fill': typeof AppToolsGenerativeFillRoute
  '/app/tools/image-expand': typeof AppToolsImageExpandRoute
  '/app/tools/image-generation': typeof AppToolsImageGenerationRoute
  '/app/tools/reimagine': typeof AppToolsReimagineRoute
  '/app/tools/relight': typeof AppToolsRelightRoute
  '/app/tools/remove-background': typeof AppToolsRemoveBackgroundRoute
  '/app/tools/runway': typeof AppToolsRunwayRoute
  '/app/tools/seedream': typeof AppToolsSeedreamRoute
  '/app/tools/seedream-edit': typeof AppToolsSeedreamEditRoute
  '/app/tools/style-transfer': typeof AppToolsStyleTransferRoute
  '/app/tools/upscaler': typeof AppToolsUpscalerRoute
  '/app/tools/video': typeof AppToolsVideoRoute
  '/app/tools/voice': typeof AppToolsVoiceRoute
  '/app/tools/z-image': typeof AppToolsZImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/admin': typeof AppAdminRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/explore': typeof AppExploreRoute
  '/app/history': typeof AppHistoryRoute
  '/app/library': typeof AppLibraryRoute
  '/app/spaces': typeof AppSpacesRoute
  '/app/': typeof AppIndexRoute
  '/api/public/magnific-webhook': typeof ApiPublicMagnificWebhookRoute
  '/app/tools/eraser': typeof AppToolsEraserRoute
  '/app/tools/flux-kontext': typeof AppToolsFluxKontextRoute
  '/app/tools/flux2': typeof AppToolsFlux2Route
  '/app/tools/generative-fill': typeof AppToolsGenerativeFillRoute
  '/app/tools/image-expand': typeof AppToolsImageExpandRoute
  '/app/tools/image-generation': typeof AppToolsImageGenerationRoute
  '/app/tools/reimagine': typeof AppToolsReimagineRoute
  '/app/tools/relight': typeof AppToolsRelightRoute
  '/app/tools/remove-background': typeof AppToolsRemoveBackgroundRoute
  '/app/tools/runway': typeof AppToolsRunwayRoute
  '/app/tools/seedream': typeof AppToolsSeedreamRoute
  '/app/tools/seedream-edit': typeof AppToolsSeedreamEditRoute
  '/app/tools/style-transfer': typeof AppToolsStyleTransferRoute
  '/app/tools/upscaler': typeof AppToolsUpscalerRoute
  '/app/tools/video': typeof AppToolsVideoRoute
  '/app/tools/voice': typeof AppToolsVoiceRoute
  '/app/tools/z-image': typeof AppToolsZImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/explore'
    | '/app/history'
    | '/app/library'
    | '/app/spaces'
    | '/app/'
    | '/api/public/magnific-webhook'
    | '/app/tools/eraser'
    | '/app/tools/flux-kontext'
    | '/app/tools/flux2'
    | '/app/tools/generative-fill'
    | '/app/tools/image-expand'
    | '/app/tools/image-generation'
    | '/app/tools/reimagine'
    | '/app/tools/relight'
    | '/app/tools/remove-background'
    | '/app/tools/runway'
    | '/app/tools/seedream'
    | '/app/tools/seedream-edit'
    | '/app/tools/style-transfer'
    | '/app/tools/upscaler'
    | '/app/tools/video'
    | '/app/tools/voice'
    | '/app/tools/z-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/explore'
    | '/app/history'
    | '/app/library'
    | '/app/spaces'
    | '/app'
    | '/api/public/magnific-webhook'
    | '/app/tools/eraser'
    | '/app/tools/flux-kontext'
    | '/app/tools/flux2'
    | '/app/tools/generative-fill'
    | '/app/tools/image-expand'
    | '/app/tools/image-generation'
    | '/app/tools/reimagine'
    | '/app/tools/relight'
    | '/app/tools/remove-background'
    | '/app/tools/runway'
    | '/app/tools/seedream'
    | '/app/tools/seedream-edit'
    | '/app/tools/style-transfer'
    | '/app/tools/upscaler'
    | '/app/tools/video'
    | '/app/tools/voice'
    | '/app/tools/z-image'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/explore'
    | '/app/history'
    | '/app/library'
    | '/app/spaces'
    | '/app/'
    | '/api/public/magnific-webhook'
    | '/app/tools/eraser'
    | '/app/tools/flux-kontext'
    | '/app/tools/flux2'
    | '/app/tools/generative-fill'
    | '/app/tools/image-expand'
    | '/app/tools/image-generation'
    | '/app/tools/reimagine'
    | '/app/tools/relight'
    | '/app/tools/remove-background'
    | '/app/tools/runway'
    | '/app/tools/seedream'
    | '/app/tools/seedream-edit'
    | '/app/tools/style-transfer'
    | '/app/tools/upscaler'
    | '/app/tools/video'
    | '/app/tools/voice'
    | '/app/tools/z-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMagnificWebhookRoute: typeof ApiPublicMagnificWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/spaces': {
      id: '/app/spaces'
      path: '/spaces'
      fullPath: '/app/spaces'
      preLoaderRoute: typeof AppSpacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/z-image': {
      id: '/app/tools/z-image'
      path: '/tools/z-image'
      fullPath: '/app/tools/z-image'
      preLoaderRoute: typeof AppToolsZImageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/voice': {
      id: '/app/tools/voice'
      path: '/tools/voice'
      fullPath: '/app/tools/voice'
      preLoaderRoute: typeof AppToolsVoiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/video': {
      id: '/app/tools/video'
      path: '/tools/video'
      fullPath: '/app/tools/video'
      preLoaderRoute: typeof AppToolsVideoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/upscaler': {
      id: '/app/tools/upscaler'
      path: '/tools/upscaler'
      fullPath: '/app/tools/upscaler'
      preLoaderRoute: typeof AppToolsUpscalerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/style-transfer': {
      id: '/app/tools/style-transfer'
      path: '/tools/style-transfer'
      fullPath: '/app/tools/style-transfer'
      preLoaderRoute: typeof AppToolsStyleTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/seedream-edit': {
      id: '/app/tools/seedream-edit'
      path: '/tools/seedream-edit'
      fullPath: '/app/tools/seedream-edit'
      preLoaderRoute: typeof AppToolsSeedreamEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/seedream': {
      id: '/app/tools/seedream'
      path: '/tools/seedream'
      fullPath: '/app/tools/seedream'
      preLoaderRoute: typeof AppToolsSeedreamRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/runway': {
      id: '/app/tools/runway'
      path: '/tools/runway'
      fullPath: '/app/tools/runway'
      preLoaderRoute: typeof AppToolsRunwayRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/remove-background': {
      id: '/app/tools/remove-background'
      path: '/tools/remove-background'
      fullPath: '/app/tools/remove-background'
      preLoaderRoute: typeof AppToolsRemoveBackgroundRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/relight': {
      id: '/app/tools/relight'
      path: '/tools/relight'
      fullPath: '/app/tools/relight'
      preLoaderRoute: typeof AppToolsRelightRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/reimagine': {
      id: '/app/tools/reimagine'
      path: '/tools/reimagine'
      fullPath: '/app/tools/reimagine'
      preLoaderRoute: typeof AppToolsReimagineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/image-generation': {
      id: '/app/tools/image-generation'
      path: '/tools/image-generation'
      fullPath: '/app/tools/image-generation'
      preLoaderRoute: typeof AppToolsImageGenerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/image-expand': {
      id: '/app/tools/image-expand'
      path: '/tools/image-expand'
      fullPath: '/app/tools/image-expand'
      preLoaderRoute: typeof AppToolsImageExpandRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/generative-fill': {
      id: '/app/tools/generative-fill'
      path: '/tools/generative-fill'
      fullPath: '/app/tools/generative-fill'
      preLoaderRoute: typeof AppToolsGenerativeFillRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/flux2': {
      id: '/app/tools/flux2'
      path: '/tools/flux2'
      fullPath: '/app/tools/flux2'
      preLoaderRoute: typeof AppToolsFlux2RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/flux-kontext': {
      id: '/app/tools/flux-kontext'
      path: '/tools/flux-kontext'
      fullPath: '/app/tools/flux-kontext'
      preLoaderRoute: typeof AppToolsFluxKontextRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/eraser': {
      id: '/app/tools/eraser'
      path: '/tools/eraser'
      fullPath: '/app/tools/eraser'
      preLoaderRoute: typeof AppToolsEraserRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/magnific-webhook': {
      id: '/api/public/magnific-webhook'
      path: '/api/public/magnific-webhook'
      fullPath: '/api/public/magnific-webhook'
      preLoaderRoute: typeof ApiPublicMagnificWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppExploreRoute: typeof AppExploreRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppSpacesRoute: typeof AppSpacesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppToolsEraserRoute: typeof AppToolsEraserRoute
  AppToolsFluxKontextRoute: typeof AppToolsFluxKontextRoute
  AppToolsFlux2Route: typeof AppToolsFlux2Route
  AppToolsGenerativeFillRoute: typeof AppToolsGenerativeFillRoute
  AppToolsImageExpandRoute: typeof AppToolsImageExpandRoute
  AppToolsImageGenerationRoute: typeof AppToolsImageGenerationRoute
  AppToolsReimagineRoute: typeof AppToolsReimagineRoute
  AppToolsRelightRoute: typeof AppToolsRelightRoute
  AppToolsRemoveBackgroundRoute: typeof AppToolsRemoveBackgroundRoute
  AppToolsRunwayRoute: typeof AppToolsRunwayRoute
  AppToolsSeedreamRoute: typeof AppToolsSeedreamRoute
  AppToolsSeedreamEditRoute: typeof AppToolsSeedreamEditRoute
  AppToolsStyleTransferRoute: typeof AppToolsStyleTransferRoute
  AppToolsUpscalerRoute: typeof AppToolsUpscalerRoute
  AppToolsVideoRoute: typeof AppToolsVideoRoute
  AppToolsVoiceRoute: typeof AppToolsVoiceRoute
  AppToolsZImageRoute: typeof AppToolsZImageRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppExploreRoute: AppExploreRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppSpacesRoute: AppSpacesRoute,
  AppIndexRoute: AppIndexRoute,
  AppToolsEraserRoute: AppToolsEraserRoute,
  AppToolsFluxKontextRoute: AppToolsFluxKontextRoute,
  AppToolsFlux2Route: AppToolsFlux2Route,
  AppToolsGenerativeFillRoute: AppToolsGenerativeFillRoute,
  AppToolsImageExpandRoute: AppToolsImageExpandRoute,
  AppToolsImageGenerationRoute: AppToolsImageGenerationRoute,
  AppToolsReimagineRoute: AppToolsReimagineRoute,
  AppToolsRelightRoute: AppToolsRelightRoute,
  AppToolsRemoveBackgroundRoute: AppToolsRemoveBackgroundRoute,
  AppToolsRunwayRoute: AppToolsRunwayRoute,
  AppToolsSeedreamRoute: AppToolsSeedreamRoute,
  AppToolsSeedreamEditRoute: AppToolsSeedreamEditRoute,
  AppToolsStyleTransferRoute: AppToolsStyleTransferRoute,
  AppToolsUpscalerRoute: AppToolsUpscalerRoute,
  AppToolsVideoRoute: AppToolsVideoRoute,
  AppToolsVoiceRoute: AppToolsVoiceRoute,
  AppToolsZImageRoute: AppToolsZImageRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMagnificWebhookRoute: ApiPublicMagnificWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
